title: Andersos
email: blog@andersos.net
description: My blog
baseurl: /
twitter: Andersos
github: Andersos
gravatar_url: https://www.gravatar.com/avatar/46f0faa6adca491c96513814e86a3a4f.jpg
google_analytics_id: UA-18605626-1

# Jekyll Settings
timezone: Europe/Oslo
markdown: kramdown
highlighter: pygments
paginate: 20
gems:
  - jekyll-redirect-from