title: Andersos
email: blog@andersos.net
twitter: Andersos
gravatar_url: https://www.gravatar.com/avatar/46f0faa6adca491c96513814e86a3a4f.jpg
baseurl: /
google_analytics_id: UA-18605626-1

# Jekyll Settings
exclude: [vendor]
timezone: Europe/Oslo
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-redirect-from