title: Anders Olsen Sandvik
url: http://andersos.net
email: blog@andersos.net
gravatar_url: https://www.gravatar.com/avatar/46f0faa6adca491c96513814e86a3a4f.jpg
baseurl: ""
google_analytics_id: UA-18605626-1
description: I make great services people like to use!

# Jekyll Settings
exclude: [vendor]
timezone: Europe/Oslo
permalink: pretty
markdown: kramdown
jekyll-mentions: https://twitter.com
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
